### ISSUE TITLE
好不容易弄好onxx运行的时候出现这个错误是什么问题

### ISSUE THREAD

**Issue by Disappointing** [liaoinstan/dnfm_server-main#1]
Traceback (most recent call last):
  File "C:\code\dnfm_server-main-main\component\ui\DrawLabel.py", line 116, in paintEvent
Exception in thread Thread-2 (thread):
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.__drawMapPoints(painter)
  File "C:\code\dnfm_server-main-main\component\ui\DrawLabel.py", line 343, in __drawMapPoints
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    drawCircle(x+offR, y+offR, r)
  File "C:\code\dnfm_server-main-main\component\ui\DrawLabel.py", line 333, in drawCircle
    painter.drawEllipse(cx - r, cy - r, 2 * r, 2 * r)
TypeError: arguments did not match any overloaded call:
  drawEllipse(self, r: QRectF): argument 1 has unexpected type 'float'
  drawEllipse(self, r: QRect): argument 1 has unexpected type 'float'
  drawEllipse(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawEllipse(self, center: Union[QPointF, QPoint], rx: float, ry: float): argument 1 has unexpected type 'float'
  drawEllipse(self, center: QPoint, rx: int, ry: int): argument 1 has unexpected type 'float'

**Comment by liaoinstan** [comment]
数据类型转换，修复了
